[FIELD]
# Caso queira modificar o nome do atributo basta descomentar a linha
layer_1 = 'Population Density Estimates in 2015 (km²)'

[PUBLISHING]
default field = '' # Se estiver vazio: Shape mostra 'Geometry', Raster mostra o primeiro layer.
download = true # true ou false, indica se vai ser possivel fazer o download do mapa
#Ex: para desabilitar os layers 'codigo' e 'codigo2', seria: disabled = ['codigo','codigo2']
disabled = [] # Lista de campos que devem ser excluidos da visualização. ( A lista pode ser em uma linha ou em várias )
listable = false # true ou false, indica se o mapa deve estar visivel na listagem
is rgb = false # true caso o mapa deva ser publicado em RGB, false caso contrário.
