# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregation_resamplingSum <- function(originalMapPath, newMapPath) {
    invisible(.Call(`_rasteraggregation_aggregation_resamplingSum`, originalMapPath, newMapPath))
}

aggregation_resamplingAverage <- function(originalMapPath, newMapPath) {
    invisible(.Call(`_rasteraggregation_aggregation_resamplingAverage`, originalMapPath, newMapPath))
}

aggregation_gdalVersion <- function() {
    .Call(`_rasteraggregation_aggregation_gdalVersion`)
}

