# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregation_resamplingSum <- function(originalMapPath, newMapPath) {
    invisible(.Call(`_rasteraggregation_aggregation_resamplingSum`, originalMapPath, newMapPath))
}

aggregation_resamplingAverage <- function(originalMapPath, newMapPath) {
    invisible(.Call(`_rasteraggregation_aggregation_resamplingAverage`, originalMapPath, newMapPath))
}

aggregation_fieldUniqueValuesString <- function(shapePath, fieldName) {
    .Call(`_rasteraggregation_aggregation_fieldUniqueValuesString`, shapePath, fieldName)
}

aggregation_sumAreaWhere <- function(shapePath, where) {
    .Call(`_rasteraggregation_aggregation_sumAreaWhere`, shapePath, where)
}

aggregation_sumAreaByValue <- function(shapePath, fieldName, fieldValue) {
    .Call(`_rasteraggregation_aggregation_sumAreaByValue`, shapePath, fieldName, fieldValue)
}

aggregation_sumAreaGroupedByColumn <- function(shapePath, fieldName) {
    .Call(`_rasteraggregation_aggregation_sumAreaGroupedByColumn`, shapePath, fieldName)
}

aggregation_init <- function() {
    .Call(`_rasteraggregation_aggregation_init`)
}

aggregation_interpretExpressionDouble <- function(curFilter, ruleValue) {
    .Call(`_rasteraggregation_aggregation_interpretExpressionDouble`, curFilter, ruleValue)
}

aggregation_interpretExpressionString <- function(curFilter, ruleValue) {
    .Call(`_rasteraggregation_aggregation_interpretExpressionString`, curFilter, ruleValue)
}

